include:
  - dependencies.yaml

services:
  booknrest:
    container_name: booknrest
    image: booknrest:latest
    build:
      context: ../
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres