include:
  - dependencies.yaml

services:
  parquimetro:
    container_name: parquimetro
    image: parquimetro:latest
    build:
      context: ../
      dockerfile: ./Dockerfile
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://admin:admin123@mongo:27017/mydatabase
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_REDIS_PASSWORD: redispassword
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - redis